# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-d7768ef2-4c7b-4d66-acec-96bd52f82e5b";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-d7768ef2-4c7b-4d66-acec-96bd52f82e5b".device = "/dev/disk/by-uuid/d7768ef2-4c7b-4d66-acec-96bd52f82e5b";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-d7768ef2-4c7b-4d66-acec-96bd52f82e5b";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-d7768ef2-4c7b-4d66-acec-96bd52f82e5b";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/747A-AC4D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2350b033-c332-4a13-9397-ab471fc83723"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
