name: NixOS Build & Cache
 
on:
  push:
    branches: [main, master]
    paths-ignore:
      - '**.md'
      - ".gitignore"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"
 
permissions:
   contents: read
   
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v6
 
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf:
            lazy-trees = true

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false
          upstream-cache: https://cache.nixos.org

      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: theneillsaaco-nix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
 
      - name: Configure Nix (cache priority)
        run: |
          echo "substituters = https://theneillsaaco-nix.cachix.org https://cache.nixos.org/" | sudo tee -a /etc/nix/nix.conf
          echo "builders-use-substitutes = true" | sudo tee -a /etc/nix/nix.conf

      - name: Check flake
        run: nix flake check --no-build
 
      - name: Build system toplevel
        run: |
          nix build .#nixosConfigurations.nixos.config.system.build.toplevel \
            --no-link \
            --print-build-logs \
            --accept-flake-config
            
      - name: Push to Cachix
        run: |
          nix path-info .#nixosConfigurations.nixos.config.system.build.toplevel | cachix push theneillsaaco-nix
 
