name: "Nix Build with nixbuild.net"

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Copiar el repositorio
      - name: Checkout code
        uses: actions/checkout@v7

      # 2. Instalar Nix en el runner de GitHub
      - name: Install Nix
        uses: cachix/install-nix-action@v31

      # 3. Configurar nixbuild.net como remote builder y caché
      - name: Setup nixbuild.net
        uses: nixbuild/nixbuild-action@v27
        with:
          auth_token: ${{ secrets.NIXBUILD_SSH_KEY }}

      # 4. Ejecutar la construcción (se enviará automáticamente a nixbuild.net)
      - name: Build Nix outputs
        run: nix build .#default
